name: Pyhton CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-add-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run the app
        run: python3 app.py

      - name: Check python version
        run: python3 --version

      - name: List files in repo
        run: ls -la
